CREATE TABLE USERS
(
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(68) NOT NULL,
    ENABLED BOOLEAN,
    PRIMARY KEY(USERNAME)
);


CREATE TABLE AUTHORITIES
(
    USERNAME VARCHAR(50) NOT NULL,
    AUTHORITY VARCHAR(68) NOT NULL,
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);

INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES('leo@gmail.com','$2a$12$aatkBX1Z3qWLQuFsWY1VNeYKTLBRO8i.ZE/lae5SeyHcdQEQxKB9i',true);

INSERT INTO AUTHORITIES VALUES('leo@gmail.com','ROLE_ADMIN');
INSERT INTO AUTHORITIES VALUES('leo@gmail.com','ROLE_MANAGER');
INSERT INTO AUTHORITIES VALUES('leo@gmail.com','ROLE_USER');

INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES('ale@gmail.com','$2a$12$aatkBX1Z3qWLQuFsWY1VNeYKTLBRO8i.ZE/lae5SeyHcdQEQxKB9i',true);

INSERT INTO AUTHORITIES VALUES('ale@gmail.com','ROLE_ADMIN');
INSERT INTO AUTHORITIES VALUES('ale@gmail.com','ROLE_MANAGER');
INSERT INTO AUTHORITIES VALUES('ale@gmail.com','ROLE_USER');
