CREATE TABLE USERS
(
    ID SERIAL not null,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(68) NOT NULL,
    TENANT VARCHAR (30) NOT NULL,
    ENABLED BOOLEAN,
    PRIMARY KEY(ID)
);


CREATE TABLE AUTHORITIES
(
    USERNAME VARCHAR(50) NOT NULL,
    AUTHORITY VARCHAR(68) NOT NULL,
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);

CREATE TABLE SERVICE_TYPE
(
    ID SERIAL NOT NULL,
    DESCRIPTION VARCHAR(80),
    DURATION_IN_MINUTES INTEGER,
    primary key (ID)
);

CREATE TABLE PROFESSIONAL
(
    ID SERIAL NOT NULL,
    NAME VARCHAR(80) NOT NULL,
    primary key (ID)
);


CREATE TABLE PROFESSIONAL_SERVICE
(
    ID SERIAL NOT NULL,
    PROFESSIONAL_ID INTEGER,
    SERVICE_TYPE_ID INTEGER,
    primary key (ID),
    FOREIGN KEY (PROFESSIONAL_ID) REFERENCES PROFESSIONAL(ID)
);

CREATE TABLE PROFESSIONAL_BLOCK_TIME_CONFIG (
    ID SERIAL NOT NULL,
    WHOLE_DAYS_OF_WEEK_BLOCKED VARCHAR(80),
    PROFESSIONAL_SERVICE_ID INTEGER,
    FOREIGN KEY (PROFESSIONAL_SERVICE_ID) REFERENCES PROFESSIONAL_SERVICE(ID),
    PRIMARY KEY (ID)
);


CREATE TABLE TIME_BLOCKED_CONFIG (
    ID SERIAL not null,
    PROFESSIONAL_BLOCK_TIME_CONFIG_ID INTEGER,
    DAY_OF_WEEK INTEGER not null,
    START_TIME TIME not null,
    END_TIME TIME not null,
    primary key (ID),
    FOREIGN KEY (PROFESSIONAL_BLOCK_TIME_CONFIG_ID) REFERENCES PROFESSIONAL_BLOCK_TIME_CONFIG(ID)
);

CREATE TABLE CUSTOMER
(
    ID SERIAL NOT NULL,
    NAME VARCHAR(80),
    EMAIL VARCHAR(50) NOT NULL,
    PHONE VARCHAR(30),
    CPF VARCHAR(12),
    BIRTH_DATE DATE,
    HEIGHT VARCHAR(4),
    WEIGHT VARCHAR(4),
    GENDER VARCHAR(1),
    primary key (ID)
);

CREATE TABLE APPOINTMENT
(
    ID SERIAL NOT NULL,
    PROFESSIONAL_SERVICE_ID INTEGER,
    CUSTOMER_ID INTEGER,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    AMOUNT_PAID DECIMAL(12,2),
    OBSERVATION VARCHAR(350),
    FOREIGN KEY (PROFESSIONAL_SERVICE_ID) REFERENCES PROFESSIONAL_SERVICE(ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID),
    PRIMARY KEY (ID)
);


CREATE TABLE PERFORMED_APPOINTMENT
(
    ID SERIAL NOT NULL,
    APPOINTMENT_ID INTEGER,
    OBSERVATIONS VARCHAR(350),
    PERFORMED_PROCEDURES VARCHAR(350),
    POST_SERVICE_PROCEDURES VARCHAR(350),
    FOREIGN KEY (APPOINTMENT_ID) REFERENCES APPOINTMENT(ID),
    PRIMARY KEY (ID)
);


CREATE TABLE ANAMNESIS
(
    ID SERIAL NOT NULL,
    DESCRIPTION VARCHAR(150) NOT NULL,
    TAGS VARCHAR(250),
    CUSTOMER_ID INTEGER,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID),
    PRIMARY KEY (ID)
);
