
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    ddl-auto: none
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
api:
  security:
    jwt:
      key: "eyJhdXRob3JpdGllcyI6IkFETUlOIiwidXNlcm5hbWUiOiJhZG1pbiJ9"

logging:
  level:
    org:
      springframework:
        dao=DEBUG:
          support=DEBUG:
        security=DEBUG:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder=TRACE:
        SQL=DEBUG:
